#!/bin/bash

mpoint=/root/install
mfile=install.sh

all_devs=$(ls /sys/class/block/*/capability | awk -F"/" '($5~/sd|mmc/)&&($0=$5)')

for dev in ${all_devs};do
	for _dev in $(ls /dev/${dev}*);do
		mount $_dev ${mpoint} 2>/dev/null
		if [ $? -eq 0 ];then
			stat ${mpoint}/${mfile} &>/dev/null
			[ $? -eq 0 ] && exit
			umount -l ${mpoint}
		fi
	done
done
