#!/bin/bash

tty=$(awk '{n=split($0,a," ");\
	for (i=1;i<=n;i++) {\
	if (a[i]~/console=/) {\
		gsub(/=|,/," ",a[i]);\
		split(a[i],b," ");\
		print b[2];}\
	}}' /proc/cmdline)

[ ! -z ${tty} ] && (ln -s /dev/${tty} /dev/ttyCompulab)
